### ISSUE TITLE
hexo generate 报错  emplate render error: (unknown path) [Line 8, Column 25]   Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]

### ISSUE THREAD

**Issue by lovepoem** [Mrminfive/hexo-theme-skapp#122]
hexo generate

```
INFO  hexo-filter-cleanup(FAVICONS): error [ Error: ENOENT: no such file or directory, access '/Users/wx/workspace/XinsBlog/theme
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 8, Column 25]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object._prettifyError (/Users/wx/workspace/XinsBlog/node_modules/nunjucks/src/lib.js:32:11)
    at /Users/wx/workspace/XinsBlog/node_modules/nunjucks/src/environment.js:464:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/wx/workspace/XinsBlog/node_modules/nunjucks/src/environment.js
    at Template.render (/Users/wx/workspace/XinsBlog/node_modules/nunjucks/src/environment.js:454:10)
    at Hexo.module.exports (/Users/wx/workspace/XinsBlog/node_modules/hexo-generator-feed/lib/generator.js:40:22)
    at Hexo.tryCatcher (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.map.key (/Users/wx/workspace/XinsBlog/node_modules/hexo/lib/hexo/index.js:332:20)
    at tryCatcher (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/map
    at MappingPromiseArray.PromiseArray._iterate (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release
    at MappingPromiseArray.init (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js
    at MappingPromiseArray._asyncInit (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/map.js:37:
    at _drainQueueStep (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/async.js:15:1
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
wx@wxs-MacBook-Pro XinsBlog % hexo generate
INFO  hexo-filter-cleanup(FAVICONS): error [ Error: ENOENT: no such file or directory, access '/Users/wx/workspace/XinsBlog/theme
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 8, Column 25]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object._prettifyError (/Users/wx/workspace/XinsBlog/node_modules/nunjucks/src/lib.js:32:11)
    at /Users/wx/workspace/XinsBlog/node_modules/nunjucks/src/environment.js:464:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/wx/workspace/XinsBlog/node_modules/nunjucks/src/environment.js
    at Template.render (/Users/wx/workspace/XinsBlog/node_modules/nunjucks/src/environment.js:454:10)
    at Hexo.module.exports (/Users/wx/workspace/XinsBlog/node_modules/hexo-generator-feed/lib/generator.js:40:22)
    at Hexo.tryCatcher (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.map.key (/Users/wx/workspace/XinsBlog/node_modules/hexo/lib/hexo/index.js:332:20)
    at tryCatcher (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/map
    at MappingPromiseArray.PromiseArray._iterate (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release
    at MappingPromiseArray.init (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js
    at MappingPromiseArray._asyncInit (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/map.js:37:
    at _drainQueueStep (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/Users/wx/workspace/XinsBlog/node_modules/hexo/node_modules/bluebird/js/release/async.js:15:1
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
````

**Comment by lovepoem** [comment]
https://github.com/Mrminfive/hexo-theme-skapp/issues/73

"lunr": "^0.7.1",
"nodejieba": "2.3.2",

修改package.json解决问题
