### ISSUE TITLE
hexo clean报错

### ISSUE THREAD

**Issue by feelscoder** [Mrminfive/hexo-theme-skapp#25]
ERROR Script load failed: themes/hexo-theme-skapp/scripts/helper.js
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)

**Comment by BruceYuj** [comment]
@feelscoder  有没有更具体的错误。 这个报的是语法出错。但是我这边并没有重现该错误。

**Comment by feelscoder** [comment]
@BruceYuj 下面就是所有的错误信息，看了好久不知道什么情况，我把_config.yml的theme主题改为其它的不会报错，改为hexo-theme-skapp就报下面的错误

lishichaodeMBP:feelscoder.github.io lishichao$ hexo clean
ERROR Script load failed: themes/hexo-theme-skapp/scripts/helper.js
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at /Users/lishichao/myBlog/feelscoder.github.io/node_modules/hexo/lib/hexo/index.js:230:17
    at tryCatcher (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/lishichao/myBlog/feelscoder.github.io/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/lishichao/myBlog/feelscoder.github.io/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
INFO  Deleted database.

**Comment by BruceYuj** [comment]
hexo s会不会报错呢？

**Comment by feelscoder** [comment]
@BruceYuj 会的，也是一样的错

**Comment by BruceYuj** [comment]
@feelscoder  我等会儿重新测试一下

**Comment by feelscoder** [comment]
@BruceYuj 恩恩，郁闷了，next的主题没问题.

**Comment by feelscoder** [comment]
Hi，能否解决

**Comment by BruceYuj** [comment]
@feelscoder  稍等，我正在pull代码

**Comment by BruceYuj** [comment]
@feelscoder  我pull最新的skapp代码，并hexo s启动了服务器，并没有出现你说的问题。
我目前怀疑是不是npm install时候，某一个插件安装失败，导致helper.js使用这个失败插件时报错。
你有没有按照readme-cn.md里面安装对应的依赖？

**Comment by feelscoder** [comment]
@BruceYuj 我去排查一下你说的这个地方

**Comment by feelscoder** [comment]
@BruceYuj 是按照readme-cn.md里面的步骤来的

**Comment by feelscoder** [comment]
lishichaodeMBP:test.github.io lishichao$ npm install --save hexo-autoprefixer hexo-filter-cleanup hexo-generator-feed hexo-generator-sitemap hexo-renderer-sass hexo-renderer-swig mamboer/lunr.js moment node-sass object-assign
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by BruceYuj** [comment]
你的系统是什么？

**Comment by feelscoder** [comment]
mac pro 10.13.1

**Comment by BruceYuj** [comment]
node version是最新的吗？

**Comment by feelscoder** [comment]
版本号是：v5.0.0

**Comment by BruceYuj** [comment]
那问题出在node的上面，因为node5.0.0不完全支持ES6的，而skapp代码用到了很多ES6的写法。
所以，你需要将你的node升级到最新的stable版本。
升级之后，最好按照步骤重新走一遍（因为某些插件会根据对应的node版本下载对应的包）

**Comment by feelscoder** [comment]
好的，我先试试。

**Comment by BruceYuj** [comment]
@feelscoder  该问题是否已解决，如果已解决，可以close

**Comment by feelscoder** [comment]
@BruceYuj 解决了，感谢耐心解答。
