### ISSUE TITLE
配置完后无法生成

### ISSUE THREAD

**Issue by imowealth** [Mrminfive/hexo-theme-skapp#58]
你好，我在配置完config文件后，然后hexo s预览，但是出现错误，clean后用generate也出现错误，麻烦指导下，谢谢。
以下是命令hexo s的打印输出：

```
INFO  index2 generators:
INFO  [ { path: '',
    per_page: 10,
    order_by: '-date',
    layout: 'index',
    index: true } ]
INFO  Start processing
INFO  hexo-filter-cleanup(FAVICONS): error [ Error: ENOENT: no such file or dire          ctory, access 'D:\ImowealthBlog\themes\hexo-theme-skapp\source\img\logo.png' ]
INFO  hexo-filter-cleanup(IMG): fonts/iconfont.svg [ 54.64% saved]
INFO  hexo-filter-cleanup(IMG): img/quotes.png [ 52.78% saved]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do          cs/troubleshooting.html
TypeError: path.substring is not a function
    at Object.urlForHelper (D:\ImowealthBlog\node_modules\hexo\lib\plugins\helpe          r\url_for.js:7:31)
    at wrapper (D:\ImowealthBlog\node_modules\lodash\lodash.js:4949:19)
    at Object.eval [as tpl] (eval at precompile (D:\ImowealthBlog\node_modules\h          exo-renderer-swig\node_modules\swig\lib\swig.js:498:13), <anonymous>:12:119)
    at compiled (D:\ImowealthBlog\node_modules\hexo-renderer-swig\node_modules\s          wig\lib\swig.js:619:18)
    at Object.eval [as tpl] (eval at precompile (D:\ImowealthBlog\node_modules\h          exo-renderer-swig\node_modules\swig\lib\swig.js:498:13), <anonymous>:6:144)
    at compiled (D:\ImowealthBlog\node_modules\hexo-renderer-swig\node_modules\s          wig\lib\swig.js:619:18)
    at Object.eval [as tpl] (eval at precompile (D:\ImowealthBlog\node_modules\h          exo-renderer-swig\node_modules\swig\lib\swig.js:498:13), <anonymous>:31:139)
    at compiled (D:\ImowealthBlog\node_modules\hexo-renderer-swig\node_modules\s          wig\lib\swig.js:619:18)
    at Theme._View.View._compiled.locals [as _compiled] (D:\ImowealthBlog\node_m          odules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (D:\ImowealthBlog\node_modules\hexo\lib\them          e\view.js:29:15)
    at route.set (D:\ImowealthBlog\node_modules\hexo\lib\hexo\index.js:386:29)
    at tryCatcher (D:\ImowealthBlog\node_modules\bluebird\js\release\util.js:16:          23)
    at D:\ImowealthBlog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\ImowealthBlog\node_modules\hexo\lib\hexo\router.js:          134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
INFO  hexo-filter-cleanup(JS): D:\ImowealthBlog\themes\hexo-theme-skapp\source\j          s\common\utils.js [ 45.85% saved]
INFO  hexo-filter-cleanup(JS): D:\ImowealthBlog\themes\hexo-theme-skapp\source\j          s\common\animation.js [ 64.76% saved]
INFO  hexo-filter-cleanup(JS): D:\ImowealthBlog\themes\hexo-theme-skapp\source\j          s\common\pack.js [ 51.37% saved]
INFO  hexo-filter-cleanup(JS): D:\ImowealthBlog\themes\hexo-theme-skapp\source\j          s\layout\loading.js [ 32.61% saved]
INFO  hexo-filter-cleanup(JS): D:\ImowealthBlog\themes\hexo-theme-skapp\source\j          s\layout\header.js [ 44.95% saved]
INFO  hexo-filter-cleanup(JS): D:\ImowealthBlog\themes\hexo-theme-skapp\source\j          s\layout\back-top.js [ 55.25% saved]
INFO  hexo-filter-cleanup(JS): D:\ImowealthBlog\themes\hexo-theme-skapp\source\j          s\layout\post.js [ 48.44% saved]
INFO  hexo-filter-cleanup(USEREF): js/common.js

```

**Comment by BruceYuj** [comment]
node版本是多少

**Comment by imowealth** [comment]
npm 5.6.0

**Comment by BruceYuj** [comment]
我的意思是nodejs的版本，不是npm包管理的版本
