### ISSUE TITLE
ERROR Script load failed: themes\hexo-theme-skapp\scripts\renderer.js

### ISSUE THREAD

**Issue by tomxin7** [Mrminfive/hexo-theme-skapp#60]
$ hexo s
ERROR Script load failed: themes\hexo-theme-skapp\scripts\renderer.js
Error: Cannot find module 'F:\code\html\hexo\node_modules\nodejieba/build/Release/nodejieba.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (F:\code\html\hexo\node_modules\nodejieba\index.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at F:\code\html\hexo\node_modules\lunr\lunr.js:199:23
    at Object.<anonymous> (F:\code\html\hexo\node_modules\lunr\lunr.js:2065:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (F:\code\html\hexo\node_modules\hexo\lib\hexo\index.js:219:21)
    at F:\code\html\hexo\themes\hexo-theme-skapp\scripts\renderer.js:5:16
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.

Windows10下，按照教程配置了，一直会报错，然后样式找不到

**Comment by tomxin7** [comment]
C:\Users\tomxin>node -v
v9.11.1

**Comment by BruceYuj** [comment]
nodejieba安装失败，之前issues里面有同样的问题，你可以去看一下。

**Comment by tomxin7** [comment]
哪一个issues，快被这个问题整崩溃了

**Comment by BruceYuj** [comment]
https://github.com/Mrminfive/hexo-theme-skapp/issues/23

**Comment by tomxin7** [comment]
你好，保证python2.7的path正确，是需要配置环境变量，然后通过cmd直接访问，代表path正确，还是说通过windows-build-tools安装成功就可以了

**Comment by BruceYuj** [comment]
正常来讲，windows-build-tools安装成功表示Python2.7的环境也配置好了。

**Comment by tomxin7** [comment]
主要我原来环境里是python3.6，所以就有点纠结会不会是python2.7没有配置好的问题

**Comment by BruceYuj** [comment]
应该不会，因为之前我用win10的电脑装的时候，里面也有python3.6

**Comment by tomxin7** [comment]
$ hexo s
ERROR Script load failed: themes\hexo-theme-skapp\scripts\renderer.js
Error: Cannot find module 'lunr'

lunr好像又找不到了，o(╥﹏╥)o

**Comment by BruceYuj** [comment]
你的步骤应该是先卸载lunr以及lunr牵扯到的依赖(比如windows-build-tools)，然后重新安装，不然卸载不干净会导致很多莫名其妙的问题。

**Comment by remember-test88** [comment]
怎么解决的 楼主
