### ISSUE TITLE
search页面的search.css报错无法加载

### ISSUE THREAD

**Issue by lyubingo** [Mrminfive/hexo-theme-skapp#65]
按照教程来的，其他都没问题，但是每次hexo g 或者 hexo d 或者 hexo s 的时候， 都无法加载？载入？写入？生成？ search.css , 不知道啥原因。

Error: Invalid CSS after "...0%) rotate(0) }": expected selector, was ","
ERROR Asset render failed: scss/views/page/search.css

报错信息段落如下：
INFO  hexo-filter-cleanup(HTML): index.html [ 39.64% saved]
INFO  hexo-filter-cleanup(HTML): tags/hexo-github/index.html [ 41.98% saved]
INFO  hexo-filter-cleanup(HTML): tags/mac/index.html [ 40.89% saved]
INFO  Files loaded in 2.5 s

> Error: Invalid CSS after "...0%) rotate(0) }": expected selector, was ","
> ERROR Asset render failed: scss/views/page/search.css
> Error: Invalid CSS after "...0%) rotate(0) }": expected selector, was ","
>     at Object.module.exports.renderSync (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/node-sass/lib/index.js:439:16)
>     at Hexo.<anonymous> (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/hexo-renderer-sass/lib/renderer.js:25:23)
>     at Promise.then.text (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/hexo/lib/hexo/render.js:61:21)
>     at tryCatcher (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/bluebird/js/release/promise.js:693:18)
>     at Async._drainQueue (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:789:20)
>     at tryOnImmediate (timers.js:751:5)
>     at processImmediate [as _immediateCallback] (timers.js:722:5)

INFO  hexo-filter-cleanup(CSS): /Users/lyubingo/blog/github/lyubingo.github.com/themes/hexo-theme-skapp/source/scss/base/index.scss [ 23.67% saved]
INFO  hexo-filter-cleanup(CSS): /Users/lyubingo/blog/github/lyubingo.github.com/themes/hexo-theme-skapp/source/scss/views/page/about.scss [ 16.35% saved]

我尝试再次创建search页面 。hexo new page search ， 会创建一个index-1.md文件。
进入public/scss/views/page查看所有都css文件，search.css 的大小为 0 kb

有谁可以帮忙解答一下吗？

**Comment by lyubingo** [comment]
这个问题我在closed里面找到答案了， 谢谢。
