### ISSUE TITLE
searchIdx.add is not a function

### ISSUE THREAD

**Issue by keiko777** [Mrminfive/hexo-theme-skapp#73]
运行代码报错
hexo s
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: searchIdx.add is not a function
    at F:\blog\themes\skapp\scripts\renderer.js:94:23
    at Array.forEach (<anonymous>)
    at Hexo.<anonymous> (F:\blog\themes\skapp\scripts\renderer.js:75:22)
    at Hexo.tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (F:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.map.key (F:\blog\node_modules\hexo\lib\hexo\index.js:336:26)
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (F:\blog\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (F:\blog\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (F:\blog\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (F:\blog\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (F:\blog\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by sxt1992** [comment]
文件: `scripts/renderer.js`

**Comment by sxt1992** [comment]
"lunr": "^0.7.1"
