### ISSUE TITLE
CentOS6安装lunr.js 报错

### ISSUE THREAD

**Issue by demonxian3** [Mrminfive/hexo-theme-skapp#85]
执行命令: 
    cnpm install --save mamboer/lunr.js
显示结果:
make: *** [Release/obj.target/nodejieba/lib/index.o] Error 1
make: Leaving directory `/root/hexo/node_modules/_nodejieba@2.2.6@nodejieba/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nodejs/node_global/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-696.30.1.el6.x86_64
gyp ERR! command "/usr/local/nodejs/bin/node" "/usr/local/nodejs/node_global/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/hexo/node_modules/_nodejieba@2.2.6@nodejieba
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
✖ Install fail! Error: Run "sh -c node-gyp rebuild" error, exit code 1
Error: Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/nodejs/node_global/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npminstall version: 3.11.0
npminstall args: /usr/local/nodejs/bin/node /usr/local/nodejs/node_global/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org --save mamboer/lunr.js

**Comment by Mrminfive** [comment]
项目依赖 nodejieba，建议去查看下文档 [doc](https://github.com/yanyiwu/nodejieba)
