### ISSUE TITLE
安装依赖的时候报错了

### ISSUE THREAD

**Issue by walersix** [Mrminfive/hexo-theme-skapp#92]
作者可以帮忙看看吗？哪里出问题了

这个是报错信息
![](https://ws1.sinaimg.cn/large/005xcdLbly1fw9u517pqbj30rq0nwgot.jpg)

系统版本，py装的是2.7的nodejs是最新的长期维护版的。
![](https://ws1.sinaimg.cn/large/005xcdLbly1fw9u62a2mgj30oc0gkt9u.jpg)

日志
[2018-10-16T01_58_44_293Z-debug.log](https://github.com/Mrminfive/hexo-theme-skapp/files/2481118/2018-10-16T01_58_44_293Z-debug.log)

**Comment by walersix** [comment]
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated browserslist@1.0.1: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated swig@1.4.2: This package is no longer maintained

> phantomjs-prebuilt@2.1.16 install D:\blog\hexo\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\ADMINI~1\AppData\Local\Temp\2\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing D:\blog\hexo\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\ADMINI~1\AppData\Local\Temp\2\phantomjs\phantomjs-2.1.1-windows.zip-extract-1539658947771\phantomjs-2.1.1-windows -> D:\blog\hexo\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at D:\blog\hexo\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> nodejieba@2.2.6 install D:\blog\hexo\node_modules\nodejieba
> node-gyp rebuild


D:\blog\hexo\node_modules\nodejieba>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
▒ڴ˽▒▒▒▒▒▒▒▒һ▒▒▒▒▒▒һ▒▒▒▒Ŀ▒▒▒▒Ҫ▒▒▒ò▒▒▒▒▒▒ɣ▒▒▒▒▒ӡ▒/m▒▒▒▒▒ء▒
MSBUILD : error MSB3428: δ▒ܼ▒▒▒ Visual C++ ▒▒▒▒▒VCBuild.exe▒▒▒▒Ҫ▒▒▒▒▒▒▒▒⣬1) ▒▒װ .NET Framework 2.0 SDK▒▒2) ▒▒װ Microsoft Visual Studio 2005▒▒▒▒ 3) ▒▒▒▒▒▒▒▒▒▒▒▒װ▒▒▒▒▒▒▒▒λ▒ã▒▒뽫▒▒λ▒▒▒▒ӵ▒ϵͳ·▒▒▒С▒ [D:\blog\hexo\node_modules\nodejieba\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\blog\hexo\node_modules\nodejieba
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejieba@2.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejieba@2.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-10-16T03_02_32_095Z-debug.log

`
还是解决不了 ennnnn

**Comment by BruceYuj** [comment]
win系统原因，node-gyp对win系统支持不好。README里面有win10的一个解决方案（不能覆盖所有的win10版本），其他的win系统可能得需要其他解决方法。 
我建议，使用linux系统。或者使用travis CI之类的集成工具

**Comment by aoaovip** [comment]
真是的，我弄了半天；win10跑起来了。就差弄弄css样式了，哎。npm包环境搞死人啊！！！！
